#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
let chalk;
const source = path.join(__dirname, '..');
const projectName = process.argv[2] ?? 'create-ts-app';
const filesToExclude = ['installer', 'node_modules', '.git'];

import('chalk').then(module => {
	chalk = module.default;

	console.log();
	console.log(chalk.magenta('Executing @dannyxcii/create-ts-app installer'));
	console.log();
	console.log('Creating your new TypeScript app:', chalk.cyan(projectName));
	console.log('Setting up project directory at', chalk.cyan(path.join(process.cwd(), projectName)));

	copyFolderToSync(source, path.join(process.cwd(), projectName));
	
	console.log('Updating your apps', chalk.cyan('package.json'));

	modifyPackageJson();

	console.log();
	console.log(chalk.greenBright('Success: Application Created'));
	console.log(chalk.italic('Now run:', chalk.yellow(`cd ${projectName} && npm install && npm run dev`)));
});

function copyFolderToSync(source, destination)
{
	fs.mkdirSync(destination, {recursive: true});
	fs.readdirSync(source).forEach(element => {
		if (filesToExclude.includes(element)) return;
		
		if (fs.lstatSync(path.join(source, element)).isFile()) {
			fs.copyFileSync(path.join(source, element), path.join(destination, element));
		} else {
			copyFolderToSync(path.join(source, element), path.join(destination, element));
		}
	});
}

function modifyPackageJson()
{
	const packageJson = require(path.join(source, 'package.json'));
	
	delete packageJson['bin'];
	delete packageJson['dependencies'];
	
	packageJson.name = projectName;

	fs.writeFileSync(
		path.join(process.cwd(), projectName, 'package.json'),
		JSON.stringify(packageJson, null, 2)
	);
}