#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const source = path.join(__dirname, '..');
const projectName = process.argv[2] ?? 'create-ts-app';

const filesToExclude = ['installer', 'node_modules', '.git'];

function copyFolderToSync(source, destination)
{
	fs.mkdirSync(destination, {recursive: true});
	fs.readdirSync(source).forEach(element => {
		if (filesToExclude.includes(element)) return;
		
		if (fs.lstatSync(path.join(source, element)).isFile()) {
			fs.copyFileSync(path.join(source, element), path.join(destination, element));
		} else {
			copyFolderToSync(path.join(source, element), path.join(destination, element));
		}
	});
}

function modifyPackageJson()
{
	const packageJson = require(path.join(source, 'package.json'));
	
	delete packageJson['bin'];
	
	packageJson.name = projectName;
	
	console.log(packageJson);

	fs.writeFileSync(
		path.join(process.cwd(), projectName, 'package.json'),
		JSON.stringify(packageJson, null, 2)
	);
}

copyFolderToSync(source, path.join(process.cwd(), projectName));
modifyPackageJson();